# Deploy Web
.PHONY: init-web
init-web:
	cd Cloud && terraform init

.PHONY: destroy-web
destroy-web:
	cd Cloud && terraform destroy

.PHONY: plan-web
plan-web:
	cd Cloud && terraform plan

.PHONY: deploy-web
deploy-web:
	cd Cloud && terraform apply