version: '3.7'
services:
  
  api:
    build: ./
    image: ems-api
    ports:
      - "5000:80"
    environment:
      - TokenKey=super sectet key
  
  localstack:
    image: localstack/localstack-light
    container_name: localstack
    ports:
      - '4566-4599:4566-4599'
      - '8080:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'