version: '3.7'
services:
  
  api:
    build: ./
    image: ems-api
    ports:
      - "5000:80"
    environment:
      - TokenKey=super sectet key
  
  localstack-s3:
    image: localstack/localstack:latest
    container_name: aws-localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'